/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as TerrasseExterieurRouteImport } from './routes/terrasse-exterieur'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RenovationCompleteRouteImport } from './routes/renovation-complete'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as PiscineSpaRouteImport } from './routes/piscine-spa'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MaconnerieGeneraleRouteImport } from './routes/maconnerie-generale'
import { Route as GuideDevisCarrelageRouteImport } from './routes/guide-devis-carrelage'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as CarrelageInterieurRouteImport } from './routes/carrelage-interieur'
import { Route as AccessibiliteRouteImport } from './routes/accessibilite'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const TerrasseExterieurRoute = TerrasseExterieurRouteImport.update({
  id: '/terrasse-exterieur',
  path: '/terrasse-exterieur',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovationCompleteRoute = RenovationCompleteRouteImport.update({
  id: '/renovation-complete',
  path: '/renovation-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const PiscineSpaRoute = PiscineSpaRouteImport.update({
  id: '/piscine-spa',
  path: '/piscine-spa',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MaconnerieGeneraleRoute = MaconnerieGeneraleRouteImport.update({
  id: '/maconnerie-generale',
  path: '/maconnerie-generale',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideDevisCarrelageRoute = GuideDevisCarrelageRouteImport.update({
  id: '/guide-devis-carrelage',
  path: '/guide-devis-carrelage',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrelageInterieurRoute = CarrelageInterieurRouteImport.update({
  id: '/carrelage-interieur',
  path: '/carrelage-interieur',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibiliteRoute = AccessibiliteRouteImport.update({
  id: '/accessibilite',
  path: '/accessibilite',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/carrelage-interieur': typeof CarrelageInterieurRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/guide-devis-carrelage': typeof GuideDevisCarrelageRoute
  '/maconnerie-generale': typeof MaconnerieGeneraleRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/piscine-spa': typeof PiscineSpaRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/realisations': typeof RealisationsRoute
  '/renovation-complete': typeof RenovationCompleteRoute
  '/services': typeof ServicesRoute
  '/terrasse-exterieur': typeof TerrasseExterieurRoute
  '/zones': typeof ZonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/carrelage-interieur': typeof CarrelageInterieurRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/guide-devis-carrelage': typeof GuideDevisCarrelageRoute
  '/maconnerie-generale': typeof MaconnerieGeneraleRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/piscine-spa': typeof PiscineSpaRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/realisations': typeof RealisationsRoute
  '/renovation-complete': typeof RenovationCompleteRoute
  '/services': typeof ServicesRoute
  '/terrasse-exterieur': typeof TerrasseExterieurRoute
  '/zones': typeof ZonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/carrelage-interieur': typeof CarrelageInterieurRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/guide-devis-carrelage': typeof GuideDevisCarrelageRoute
  '/maconnerie-generale': typeof MaconnerieGeneraleRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/piscine-spa': typeof PiscineSpaRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/realisations': typeof RealisationsRoute
  '/renovation-complete': typeof RenovationCompleteRoute
  '/services': typeof ServicesRoute
  '/terrasse-exterieur': typeof TerrasseExterieurRoute
  '/zones': typeof ZonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/accessibilite'
    | '/carrelage-interieur'
    | '/cgu'
    | '/cgv'
    | '/contact'
    | '/guide-devis-carrelage'
    | '/maconnerie-generale'
    | '/mentions-legales'
    | '/piscine-spa'
    | '/politique-confidentialite'
    | '/realisations'
    | '/renovation-complete'
    | '/services'
    | '/terrasse-exterieur'
    | '/zones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/accessibilite'
    | '/carrelage-interieur'
    | '/cgu'
    | '/cgv'
    | '/contact'
    | '/guide-devis-carrelage'
    | '/maconnerie-generale'
    | '/mentions-legales'
    | '/piscine-spa'
    | '/politique-confidentialite'
    | '/realisations'
    | '/renovation-complete'
    | '/services'
    | '/terrasse-exterieur'
    | '/zones'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/accessibilite'
    | '/carrelage-interieur'
    | '/cgu'
    | '/cgv'
    | '/contact'
    | '/guide-devis-carrelage'
    | '/maconnerie-generale'
    | '/mentions-legales'
    | '/piscine-spa'
    | '/politique-confidentialite'
    | '/realisations'
    | '/renovation-complete'
    | '/services'
    | '/terrasse-exterieur'
    | '/zones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AccessibiliteRoute: typeof AccessibiliteRoute
  CarrelageInterieurRoute: typeof CarrelageInterieurRoute
  CguRoute: typeof CguRoute
  CgvRoute: typeof CgvRoute
  ContactRoute: typeof ContactRoute
  GuideDevisCarrelageRoute: typeof GuideDevisCarrelageRoute
  MaconnerieGeneraleRoute: typeof MaconnerieGeneraleRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PiscineSpaRoute: typeof PiscineSpaRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  RealisationsRoute: typeof RealisationsRoute
  RenovationCompleteRoute: typeof RenovationCompleteRoute
  ServicesRoute: typeof ServicesRoute
  TerrasseExterieurRoute: typeof TerrasseExterieurRoute
  ZonesRoute: typeof ZonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terrasse-exterieur': {
      id: '/terrasse-exterieur'
      path: '/terrasse-exterieur'
      fullPath: '/terrasse-exterieur'
      preLoaderRoute: typeof TerrasseExterieurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovation-complete': {
      id: '/renovation-complete'
      path: '/renovation-complete'
      fullPath: '/renovation-complete'
      preLoaderRoute: typeof RenovationCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piscine-spa': {
      id: '/piscine-spa'
      path: '/piscine-spa'
      fullPath: '/piscine-spa'
      preLoaderRoute: typeof PiscineSpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maconnerie-generale': {
      id: '/maconnerie-generale'
      path: '/maconnerie-generale'
      fullPath: '/maconnerie-generale'
      preLoaderRoute: typeof MaconnerieGeneraleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide-devis-carrelage': {
      id: '/guide-devis-carrelage'
      path: '/guide-devis-carrelage'
      fullPath: '/guide-devis-carrelage'
      preLoaderRoute: typeof GuideDevisCarrelageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrelage-interieur': {
      id: '/carrelage-interieur'
      path: '/carrelage-interieur'
      fullPath: '/carrelage-interieur'
      preLoaderRoute: typeof CarrelageInterieurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibilite': {
      id: '/accessibilite'
      path: '/accessibilite'
      fullPath: '/accessibilite'
      preLoaderRoute: typeof AccessibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AccessibiliteRoute: AccessibiliteRoute,
  CarrelageInterieurRoute: CarrelageInterieurRoute,
  CguRoute: CguRoute,
  CgvRoute: CgvRoute,
  ContactRoute: ContactRoute,
  GuideDevisCarrelageRoute: GuideDevisCarrelageRoute,
  MaconnerieGeneraleRoute: MaconnerieGeneraleRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PiscineSpaRoute: PiscineSpaRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  RealisationsRoute: RealisationsRoute,
  RenovationCompleteRoute: RenovationCompleteRoute,
  ServicesRoute: ServicesRoute,
  TerrasseExterieurRoute: TerrasseExterieurRoute,
  ZonesRoute: ZonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
